doodle_homepage:
  path: /
  defaults: { _controller: DoodleBundle:Default:index }

doodle_questions:
    resource: "@DoodleBundle/Resources/config/routes/questions.yml"
    prefix: /question

doodle_answers:
  resource: "@DoodleBundle/Resources/config/routes/answers.yml"
  prefix: /answer

