services:
#    doodle.example:
#        class: DoodleBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    db.facade.questions:
        class: DoodleBundle\Persistence\QuestionFacade
        arguments:
            - "@doctrine.orm.entity_manager"
